CREATE DATABASE ESTAGIARIO_EDU

-- DROP DATABASE ESTAGIARIO_EDU

USE ESTAGIARIO_EDU;

CREATE TABLE CLIENTE(
	COD_CLIENTE INT IDENTITY(1,1) NOT NULL,
	NOME	VARCHAR(100),
	RG		VARCHAR(20),
	CONSTRAINT PK_COD_CLIENTE PRIMARY KEY(COD_CLIENTE)
);

CREATE TABLE PRODUTO(
	COD_PRODUTO INT IDENTITY(1,1) NOT NULL,
	DESCRICAO		VARCHAR(100),
	PRECO			DECIMAL(18,2),
	DATA_VALIDADE	SMALLDATETIME,
	CONSTRAINT PK_COD_PRODUTO PRIMARY KEY(COD_PRODUTO)
);

CREATE TABLE COMPRA(
	COD_COMPRA  INT IDENTITY(1,1) NOT NULL,
	DATA		DATETIME,
	COD_CLIENTE INT,
	VALOR_TOTAL DECIMAL(18,2),
	CONSTRAINT PK_COD_COMPRA PRIMARY KEY(COD_COMPRA),
	CONSTRAINT FK_COD_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);


CREATE TABLE ITENS_COMPRA(
	COD_ITEM_COMPRA INT IDENTITY(1,1) NOT NULL,
	COD_PRODUTO INT,
	QUANTIDADE INT NOT NULL,
	CONSTRAINT PK_COD_ITEM_COMPRA PRIMARY KEY(COD_ITEM_COMPRA),
	CONSTRAINT FK_COD_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);

ALTER TABLE ITENS_COMPRA 
ADD COD_COMPRA INT, CONSTRAINT FK_COD_COMPRA FOREIGN KEY(COD_COMPRA) REFERENCES COMPRA(COD_COMPRA)

--- INSERIR 3 REGISTROS NA TABELA CLIENTE E PRODUTO

-- CLIENTE
INSERT INTO CLIENTE(NOME,RG) VALUES('ADALBERTO DIAS','52.132.255-78');
INSERT INTO CLIENTE(NOME,RG) VALUES('JULIANA CRISTINA SILVA','54.212.082-02');
INSERT INTO CLIENTE(NOME,RG) VALUES('CRISTIAN HENRIQUE PAULISTA','27.332.764-12');
SELECT * FROM CLIENTE

-- PRODUTO

INSERT INTO PRODUTO(DESCRICAO,PRECO,DATA_VALIDADE) VALUES('LEITE', 5.29, 2022-05-01 );
INSERT INTO PRODUTO(DESCRICAO,PRECO,DATA_VALIDADE) VALUES('OVO 6 UN', 9.59, 2022-02-01 );
INSERT INTO PRODUTO(DESCRICAO,PRECO,DATA_VALIDADE) VALUES('SUCO LARANJA 1 LT', 6.99, 2022-08-21 );
SELECT * FROM PRODUTO

-- ITENS_ COMPRA

INSERT INTO ITENS_COMPRA(COD_PRODUTO, QUANTIDADE) VALUES(1, 18);
INSERT INTO ITENS_COMPRA(COD_PRODUTO, QUANTIDADE) VALUES(2, 34);
INSERT INTO ITENS_COMPRA(COD_PRODUTO, QUANTIDADE) VALUES(3, 12);

SELECT * FROM ITENS_COMPRA;


INSERT INTO ITENS_COMPRA(COD_PRODUTO, QUANTIDADE, COD_COMPRA) VALUES(1,1,2);
INSERT INTO ITENS_COMPRA(COD_PRODUTO, QUANTIDADE, COD_COMPRA) VALUES(1,1,3);
INSERT INTO ITENS_COMPRA(COD_PRODUTO, QUANTIDADE, COD_COMPRA) VALUES(3,1,3);

-- COMPRA

INSERT INTO COMPRA(DATA,COD_CLIENTE,VALOR_TOTAL) VALUES(2021-08-02, 1, 5.29+9.59);
INSERT INTO COMPRA(DATA,COD_CLIENTE,VALOR_TOTAL) VALUES(2021-08-02, 2, 6.99+9.59);
INSERT INTO COMPRA(DATA,COD_CLIENTE,VALOR_TOTAL) VALUES(2021-08-02, 3, 5.29+6.99);
SELECT * FROM COMPRA





-- ALTERANDO REGISTRO 

-- CLIENTE 

UPDATE CLIENTE
SET NOME='ANNE KINGS'
WHERE COD_CLIENTE = 1

-- COMPRA

UPDATE COMPRA
SET VALOR_TOTAL = 5.29+6.99
WHERE COD_COMPRA = 3

--TABELA ITENS COMPRA 
UPDATE ITENS_COMPRA
SET COD_COMPRA = 1, QUANTIDADE = 1
WHERE COD_ITEM_COMPRA IN (1,2)

UPDATE ITENS_COMPRA
SET COD_COMPRA = 2, QUANTIDADE = 1
WHERE COD_ITEM_COMPRA = 3

UPDATE ITENS_COMPRA
SET COD_PRODUTO = 2 
WHERE COD_ITEM_COMPRA = 4

-- PRODUTO

UPDATE PRODUTO
SET DESCRICAO = 'AVEIA PCT 850GR'
WHERE COD_PRODUTO = 2

---- DELETAR REGISTRO DE CADA TABELA

DELETE ITENS_COMPRA
WHERE COD_ITEM_COMPRA = 5

DELETE COMPRA
WHERE COD_COMPRA = 3

DELETE CLIENTE
WHERE COD_CLIENTE = 3

DELETE PRODUTO
WHERE COD_PRODUTO = 3

--- ADICIONANDO CAMPO NA TABELA

ALTER TABLE CLIENTE ADD ATIVO BIT DEFAULT 1
SELECT * FROM CLIENTE

ALTER TABLE PRODUTO ADD ATIVO BIT DEFAULT 1
SELECT * FROM PRODUTO

--- ADICIONADO O CAMPO PARA PRODUTOS NÃO VALIDADE COMO
---- SEM VALIDADE

ALTER TABLE PRODUTO
ADD SEM_VALIDADE BIT



-- COMANDOS DE TESTE NA CRIAÇÃO DE INSERT E SELECT NO FORM COMPRA

SELECT COD_COMPRA
FROM COMPRA
WHERE COD_CLIENTE = '2'
AND VALOR_TOTAL =56.35
AND DATA ='31/08/2021'


select * from itens_compra

delete from compra
where cod_compra in (5,6,7,8,9,10,11 ,13,14,15 ,16, 17,18)

SELECT *
FROM COMPRA
WHERE COD_CLIENTE = '2'
AND VALOR_TOTAL =25.68
AND DATA ='31/08/2021'


SELECT C.COD_COMPRA, C.DATA, C.COD_CLIENTE, C.VALOR_TOTAL, L.COD_CLIENTE, L.RG, L.NOME
from COMPRA C
INNER JOIN CLIENTE L ON C.COD_CLIENTE = L.COD_CLIENTE
WHERE COD_COMPRA = 19



--- comandos utilizados na tela de consulta e edição de dados da compra
--- as respectivas tabelas COMPRA E ITENS_COMPRA

SELECT I.COD_COMPRA, C.COD_COMPRA, I.COD_ITEM_COMPRA, P.COD_PRODUTO ,P.DESCRICAO, I.QUANTIDADE, C.VALOR_TOTAL 
FROM ITENS_COMPRA AS I
INNER JOIN COMPRA C 
ON C.COD_COMPRA = I.COD_COMPRA
INNER JOIN PRODUTO  P  
ON I.COD_PRODUTO = P.COD_PRODUTO
WHERE C.COD_COMPRA = 20

COUNT(COD_ITEM_COMPRA) AS QUANTIDADE


SELECT * FROM COMPRA

SELECT P.COD_PRODUTO ,P.DESCRICAO, P.PRECO , I.QUANTIDADE, C.VALOR_TOTAL
FROM ITENS_COMPRA AS I 
INNER JOIN COMPRA C
ON C.COD_COMPRA = I.COD_COMPRA
INNER JOIN PRODUTO  P
ON I.COD_PRODUTO = P.COD_PRODUTO
WHERE C.COD_COMPRA = 1


 SELECT P.COD_COMPRA, P.COD_CLIENTE , C.RG , C.NOME AS CLIENTE, P.DATA AS DATA , P.VALOR_TOTAL


SELECT * FROM ITENS_COMPRA

DELETE ITENS_COMPRA
WHERE ITENS_COMPRA.COD_COMPRA = 21




UPDATE COMPRA 
SET  DATA = '02/09/2021'
, COD_CLIENTE = '3'
, VALOR_TOTAL = 124.98
WHERE COD_COMPRA = 3


DELETE ITENS_COMPRA
WHERE COD_ITEM_COMPRA IN ()


DELETE ITENS_COMPRA
WHERE COD_ITEM_COMPRA IN (
11
)


UPDATE COMPRA 
SET  DATA = '02/09/2021'
, COD_CLIENTE = '16'
, VALOR_TOTAL = 17.38
WHERE COD_COMPRA = 20


UPDATE COMPRA 
SET  DATA = '02/09/2021'
, COD_CLIENTE = '2'
, VALOR_TOTAL = -7.79
WHERE COD_COMPRA = 2


DELETE ITENS_COMPRA
WHERE COD_PRODUTO IN (
11
)


---  Comandos utilizados para a QProduto  no formulário Compra, para consultar os produtos na tabela Itens_compra
--- saber e identificar a lista de compra ou o carrinho de compra

SELECT I.COD_PRODUTO, P.DESCRICAO, P.PRECO, I.QUANTIDADE, P.PRECO * I.QUANTIDADE AS VALOR
FROM ITENS_COMPRA I
INNER JOIN COMPRA AS C ON C.COD_COMPRA = I.COD_COMPRA
INNER JOIN PRODUTO AS P ON P.COD_PRODUTO = I.COD_PRODUTO
WHERE C.COD_COMPRA = 24

GROUP BY I.COD_ITEM_COMPRA


SELECT * FROM COMPRA

SELECT P.COD_COMPRA, P.COD_CLIENTE , C.RG  , P.VALOR_TOTAL
FROM COMPRA P
INNER JOIN CLIENTE AS C ON C.COD_CLIENTE = P.COD_CLIENTE